CREATE DATABASE demo_db;


--Create table contacts
CREATE TABLE IF NOT EXISTS contacts
( id INTEGER NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
);